opam-version: "2.0"
lib: [
  "_build/install/default/lib/qcheck-alcotest/META"
  "_build/install/default/lib/qcheck-alcotest/QCheck_alcotest.ml"
  "_build/install/default/lib/qcheck-alcotest/QCheck_alcotest.mli"
  "_build/install/default/lib/qcheck-alcotest/dune-package"
  "_build/install/default/lib/qcheck-alcotest/opam"
  "_build/install/default/lib/qcheck-alcotest/qCheck_alcotest.cmi"
  "_build/install/default/lib/qcheck-alcotest/qCheck_alcotest.cmt"
  "_build/install/default/lib/qcheck-alcotest/qCheck_alcotest.cmti"
  "_build/install/default/lib/qcheck-alcotest/qCheck_alcotest.cmx"
  "_build/install/default/lib/qcheck-alcotest/qcheck_alcotest.a"
  "_build/install/default/lib/qcheck-alcotest/qcheck_alcotest.cma"
  "_build/install/default/lib/qcheck-alcotest/qcheck_alcotest.cmxa"
]
doc: [
  "_build/install/default/doc/qcheck-alcotest/CHANGELOG.md"
  "_build/install/default/doc/qcheck-alcotest/LICENSE"
  "_build/install/default/doc/qcheck-alcotest/README.adoc"
]
libexec: "_build/install/default/lib/qcheck-alcotest/qcheck_alcotest.cmxs"
